[[mgr.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on = "<F3>"
run = "plugin toggle-pane min-preview"
desc = "Toggle preview pane"

[[mgr.prepend_keymap]]
on = "<F4>"
run = "plugin toggle-pane max-preview"
desc = "Maximize / restore preview pane"
